highlighter: pygments
markdown: redcarpet
name: Elliot Levin
sub-header: I enjoy making things
url: https://timetoogo.github.io

collections:
  stuff:
    output: true
  work:
    output: true

gems:
  - jekyll-sitemap